name: Deploy to Vercel
on:
  push:
    branches:
      - main
      - "dev-*" # dev-new-feature dev-this-new
      - "feat/**" # feat/new feat/new/button
      - development
    # paths-ignore:
    #   - ".github/workflows/*"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Verify code quality
        run: npm run lint
  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
            .eslintrc.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deployed to Vercel!"
  # sonarqube:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code from repository
  #       uses: actions/checkout@v3
  #     - name: Install NodeJS
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run SonarQube
  #       run: npm run sonarqube
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
