name: Deploy project
on: [push, workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to Vercel
        run: echo "Deploying to Vercel, sis!"
  # sonarqube:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code from repository
  #       uses: actions/checkout@v3
  #     - name: Install NodeJS
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run SonarQube
  #       run: npm run sonarqube
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
