name: Output information
on:
  issues:
    types: [opened]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context event
        run: echo "${{ toJson(github.event) }}"
