name: Reusable deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact file
        required: false
        default: dist
        type: string
    secrets:
      some-secret:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List all files
        run: ls
      - name: Output secret information
        run: echo ${{ secrets.some-secret }}
      - name: Output information
        run: echo "Deploying and uploading.."
